"""add_operator_experience_sizes

Revision ID: 4324281308a3
Revises: 64953d96e4b9
Create Date: 2026-06-03 18:32:32.206650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4324281308a3'
down_revision: Union[str, None] = '64953d96e4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('has_protocol_experience', sa.Boolean(), nullable=True, comment='Experiencia en protocolo'))
    op.add_column('operators', sa.Column('event_size_experience', sa.String(length=50), nullable=True, comment='Tamaño evento: 100,500,1000,2000+'))
    op.add_column('operators', sa.Column('locality', sa.String(length=150), nullable=True, comment='Localidad/Barrio'))
    op.add_column('operators', sa.Column('whatsapp', sa.String(length=20), nullable=True, comment='Número WhatsApp'))
    op.add_column('operators', sa.Column('shoe_size', sa.String(length=10), nullable=True))
    op.add_column('operators', sa.Column('shirt_size', sa.String(length=10), nullable=True))
    op.add_column('operators', sa.Column('pants_size', sa.String(length=10), nullable=True))
    op.add_column('operators', sa.Column('jacket_size', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'jacket_size')
    op.drop_column('operators', 'pants_size')
    op.drop_column('operators', 'shirt_size')
    op.drop_column('operators', 'shoe_size')
    op.drop_column('operators', 'whatsapp')
    op.drop_column('operators', 'locality')
    op.drop_column('operators', 'event_size_experience')
    op.drop_column('operators', 'has_protocol_experience')
    # ### end Alembic commands ###
