"""initial schema

Revision ID: 64953d96e4b9
Revises: 
Create Date: 2026-06-03 16:33:09.540268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64953d96e4b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arl',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_arl_id'), 'arl', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('eps',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_eps_id'), 'eps', ['id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('token_jti', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True, comment='logout | password_change | admin_revocation'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_token_jti'), 'revoked_tokens', ['token_jti'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True, comment='Tarifa base por turno'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='superadmin | coordinator | operator'),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_document_number'), 'users', ['document_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('setup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft | published | in_progress | completed | cancelled'),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('client_name', sa.String(length=300), nullable=True),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('operators',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('eps_id', sa.Uuid(), nullable=True),
    sa.Column('arl_id', sa.Uuid(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('photo_thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('background_check_status', sa.String(length=20), nullable=False, comment='pending | approved | rejected'),
    sa.Column('background_check_date', sa.Date(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True, comment='Promedio de evaluaciones'),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['arl_id'], ['arl.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_id'), 'operators', ['id'], unique=False)
    op.create_index(op.f('ix_operators_user_id'), 'operators', ['user_id'], unique=True)
    op.create_table('evaluations',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('evaluated_by', sa.Uuid(), nullable=True),
    sa.Column('punctuality_score', sa.Integer(), nullable=False, comment='1-5'),
    sa.Column('performance_score', sa.Integer(), nullable=False, comment='1-5'),
    sa.Column('appearance_score', sa.Integer(), nullable=False, comment='1-5'),
    sa.Column('attitude_score', sa.Integer(), nullable=False, comment='1-5'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Promedio ponderado'),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('would_hire_again', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_event_id'), 'evaluations', ['event_id'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluations_operator_id'), 'evaluations', ['operator_id'], unique=False)
    op.create_table('event_assignments',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='invited | confirmed | rejected | standby | no_show | checked_in'),
    sa.Column('whatsapp_message_id', sa.String(length=200), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('rate_applied', sa.Float(), nullable=True, comment='Tarifa aplicada al momento de asignación'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_assignments_event_id'), 'event_assignments', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_assignments_id'), 'event_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_event_assignments_operator_id'), 'event_assignments', ['operator_id'], unique=False)
    op.create_index(op.f('ix_event_assignments_status'), 'event_assignments', ['status'], unique=False)
    op.create_table('event_staff_needs',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_needed', sa.Integer(), nullable=False),
    sa.Column('quantity_confirmed', sa.Integer(), nullable=False),
    sa.Column('rate_per_shift', sa.Float(), nullable=True, comment='Tarifa para este evento/rol'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_staff_needs_event_id'), 'event_staff_needs', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_staff_needs_id'), 'event_staff_needs', ['id'], unique=False)
    op.create_index(op.f('ix_event_staff_needs_role_id'), 'event_staff_needs', ['role_id'], unique=False)
    op.create_table('sync_sessions',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('synced_by', sa.Uuid(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False, comment='download (pre-event) | upload (post-event)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | in_progress | completed | failed'),
    sa.Column('records_total', sa.Integer(), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('sync_token', sa.String(length=100), nullable=True, comment='Token efímero de un solo uso'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synced_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_sessions_event_id'), 'sync_sessions', ['event_id'], unique=False)
    op.create_index(op.f('ix_sync_sessions_id'), 'sync_sessions', ['id'], unique=False)
    op.create_table('attendance_log',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_method', sa.String(length=20), nullable=False, comment='qr | pdf417 | manual | nfc'),
    sa.Column('scanned_code', sa.String(length=200), nullable=True, comment='Código QR/PDF417 escaneado'),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('sync_session_id', sa.Uuid(), nullable=True),
    sa.Column('is_offline', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['event_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_log_event_id'), 'attendance_log', ['event_id'], unique=False)
    op.create_index(op.f('ix_attendance_log_id'), 'attendance_log', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_log_operator_id'), 'attendance_log', ['operator_id'], unique=False)
    op.create_table('payroll',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('rate_per_hour', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='calculated | pending_signature | signed | approved | paid'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='cash | transfer | nequi | daviplata'),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['event_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_event_id'), 'payroll', ['event_id'], unique=False)
    op.create_index(op.f('ix_payroll_id'), 'payroll', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_operator_id'), 'payroll', ['operator_id'], unique=False)
    op.create_index(op.f('ix_payroll_status'), 'payroll', ['status'], unique=False)
    op.create_table('whatsapp_outbound_queue',
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_params', sa.Text(), nullable=True, comment='JSON con parámetros de la plantilla'),
    sa.Column('message_type', sa.String(length=30), nullable=False, comment='invitation | reminder_5d | reminder_1d | custom'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | sent | delivered | read | failed'),
    sa.Column('meta_message_id', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['event_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_outbound_queue_event_id'), 'whatsapp_outbound_queue', ['event_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_outbound_queue_id'), 'whatsapp_outbound_queue', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_outbound_queue_phone_number'), 'whatsapp_outbound_queue', ['phone_number'], unique=False)
    op.create_index(op.f('ix_whatsapp_outbound_queue_status'), 'whatsapp_outbound_queue', ['status'], unique=False)
    op.create_table('signatures',
    sa.Column('payroll_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=False, comment='Base64 del trazo canvas'),
    sa.Column('signature_hash', sa.String(length=128), nullable=False, comment='SHA-256 hash de verificación'),
    sa.Column('signed_at', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=300), nullable=True),
    sa.Column('is_offline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_index(op.f('ix_signatures_operator_id'), 'signatures', ['operator_id'], unique=False)
    op.create_index(op.f('ix_signatures_payroll_id'), 'signatures', ['payroll_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_payroll_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_operator_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_whatsapp_outbound_queue_status'), table_name='whatsapp_outbound_queue')
    op.drop_index(op.f('ix_whatsapp_outbound_queue_phone_number'), table_name='whatsapp_outbound_queue')
    op.drop_index(op.f('ix_whatsapp_outbound_queue_id'), table_name='whatsapp_outbound_queue')
    op.drop_index(op.f('ix_whatsapp_outbound_queue_event_id'), table_name='whatsapp_outbound_queue')
    op.drop_table('whatsapp_outbound_queue')
    op.drop_index(op.f('ix_payroll_status'), table_name='payroll')
    op.drop_index(op.f('ix_payroll_operator_id'), table_name='payroll')
    op.drop_index(op.f('ix_payroll_id'), table_name='payroll')
    op.drop_index(op.f('ix_payroll_event_id'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_index(op.f('ix_attendance_log_operator_id'), table_name='attendance_log')
    op.drop_index(op.f('ix_attendance_log_id'), table_name='attendance_log')
    op.drop_index(op.f('ix_attendance_log_event_id'), table_name='attendance_log')
    op.drop_table('attendance_log')
    op.drop_index(op.f('ix_sync_sessions_id'), table_name='sync_sessions')
    op.drop_index(op.f('ix_sync_sessions_event_id'), table_name='sync_sessions')
    op.drop_table('sync_sessions')
    op.drop_index(op.f('ix_event_staff_needs_role_id'), table_name='event_staff_needs')
    op.drop_index(op.f('ix_event_staff_needs_id'), table_name='event_staff_needs')
    op.drop_index(op.f('ix_event_staff_needs_event_id'), table_name='event_staff_needs')
    op.drop_table('event_staff_needs')
    op.drop_index(op.f('ix_event_assignments_status'), table_name='event_assignments')
    op.drop_index(op.f('ix_event_assignments_operator_id'), table_name='event_assignments')
    op.drop_index(op.f('ix_event_assignments_id'), table_name='event_assignments')
    op.drop_index(op.f('ix_event_assignments_event_id'), table_name='event_assignments')
    op.drop_table('event_assignments')
    op.drop_index(op.f('ix_evaluations_operator_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_event_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_operators_user_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_document_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_token_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_eps_id'), table_name='eps')
    op.drop_table('eps')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_arl_id'), table_name='arl')
    op.drop_table('arl')
    # ### end Alembic commands ###
